version: "3.7"
services:
  web:
    build:
      context: "./ui"
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - "./ui:/app"
      - "/app/node_modules"
    depends_on:
      - api
      - maps
  api:
    container_name: graffiti-api
    build:
      context: "./api"
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - "./api:/app"
      - "/app/node_modules"
    depends_on:
      - postgres
  postgres:
    image: "postgres:12"
    container_name: postgres-db
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
